### ISSUE TITLE
pt list raises NoMethodError

### ISSUE THREAD

**Issue by bhenderson** [raul/pt#74]
```
/Users/bhenderson/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pt-0.10.0/lib/pt/data_row.rb:21:in `method_missing': undefined method `name' for #<TrackerApi::Resources::ProjectMembership id=123> (NoMethodError)
	from /Users/bhenderson/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/hirb-0.7.3/lib/hirb/helpers/object_table.rb:10:in `block (2 levels) in render'
	from /Users/bhenderson/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/hirb-0.7.3/lib/hirb/helpers/object_table.rb:10:in `each'
	from /Users/bhenderson/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/hirb-0.7.3/lib/hirb/helpers/object_table.rb:10:in `inject'
	from /Users/bhenderson/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/hirb-0.7.3/lib/hirb/helpers/object_table.rb:10:in `block in render'
	from /Users/bhenderson/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/hirb-0.7.3/lib/hirb/helpers/object_table.rb:9:in `each'
	from /Users/bhenderson/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/hirb-0.7.3/lib/hirb/helpers/object_table.rb:9:in `inject'
	from /Users/bhenderson/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/hirb-0.7.3/lib/hirb/helpers/object_table.rb:9:in `render'
	from /Users/bhenderson/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/hirb-0.7.3/lib/hirb/helpers/auto_table.rb:22:in `render'
	from /Users/bhenderson/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/hirb-0.7.3/lib/hirb/formatter.rb:73:in `_format_output'
	from /Users/bhenderson/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/hirb-0.7.3/lib/hirb/formatter.rb:56:in `format_output'
	from /Users/bhenderson/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/hirb-0.7.3/lib/hirb/view.rb:205:in `render_output'
	from /Users/bhenderson/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/hirb-0.7.3/lib/hirb/console.rb:18:in `render_output'
	from /Users/bhenderson/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/hirb-0.7.3/lib/hirb/console.rb:30:in `table'
	from /Users/bhenderson/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pt-0.10.0/lib/pt/data_table.rb:27:in `print'
	from /Users/bhenderson/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pt-0.10.0/lib/pt/helper.rb:233:in `select'
	from /Users/bhenderson/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pt-0.10.0/lib/pt/cli.rb:76:in `list'
	from /Users/bhenderson/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /Users/bhenderson/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/bhenderson/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /Users/bhenderson/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /Users/bhenderson/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pt-0.10.0/bin/pt:10:in `<top (required)>'
	from /Users/bhenderson/.rbenv/versions/2.4.1/bin/pt:23:in `load'
	from /Users/bhenderson/.rbenv/versions/2.4.1/bin/pt:23:in `<main>'
```

This is a fresh install of the gem.
thanks

**Comment by drselump14** [comment]
I'm afraid I don't have time to check this issue right now. Pull request are welcomed.
You'd probably want to try [ipt](https://github.com/drselump14/ipt) while I'm trying to address this issue.

**Comment by stealthybox** [comment]
I'm able to reproduce.
